# docker-compose-blue.yml
version: '3'
services:
  backend:
    build: .
    container_name: ${DOCKER_APP_NAME}-blue
    environment:
      - LANG=ko_KR.UTF-8
      - UWSGI_PORT=8080
    ports:
      - "8089:8080"
    volumes:
      - /home/ubuntu/app/logs/blue:/log