#green
version: '3'
services:
  backend:
    build: .
    container_name: spring-green
    environment:
      - LANG=ko_KR.UTF-8
      - UWSGI_PORT=8080
    ports:
      - "8090:8080"
    volumes:
      - /home/ubuntu/app/logs/green:/log