#green
version: '3'
services:
  api:
    image: ${DOCKER_REGISTRY}/${DOCKER_APP_NAME}:${IMAGE_TAG}

    container_name: ${DOCKER_APP_NAME}-green

    environment:
      - LANG=ko_KR.UTF-8
      - UWSGI_PORT=8080

    ports:
      - "8090:8080"