version: "2.1"
services:
  spring1:
    build: .
    image: spring
    container_name: real1
    ports:
      - '8089:8089'
    volumes:
      - ./:/root/
    environment:
      active: real1
  spring2:
    build: .
    image: spring
    container_name: real2
    ports:
      - '8090:8090'
    volumes:
      - ./:/root/
    environment:
      active: real2